### ISSUE TITLE
How can i translate the research requirements mod?

### ISSUE THREAD

**Issue by Nipodemos** [pether-pg/ONI_Mods_byPether#10]
hello!
I've looked in the fold of the research requirements mod, but didn't found any .json or .po files that contain the strings, the closest to that was the STRINGS.cs file, but i never coded with C# and even so, i don't know what file to update.
Could you teach me that? I will happily translate that send a PR after that 😃

**Comment by pether-pg** [comment]
There is researchrequirements_template.pot file in Translations directory. Load this file in PoEdit application to generate *.po file with translations to the language you choose. For more details, see https://forums.kleientertainment.com/forums/topic/74765-creatingusing-translation-files-updated-august-22nd-2017/

If you don't see Translations directory in your mod root folder, use "Mod Updater" to update your mod or get .pot file from my github from UploadFiles_Steam\ResearchRequirements\Translations

Thanks!
