### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by TheRealAyCe** [pether-pg/ONI_Mods_byPether#15]
https://github.com/pether-pg/ONI_Mods_byPether/blob/master/InterplanarAutomation/WarpBridgeData.cs

Incomming -> Incoming
Transmited -> Transmitted

Or is this a joke on comms and mites?

**Comment by pether-pg** [comment]
Thanks a lot!
Those are typos, I sometimes make them.
Currently I don't have access to my modding PC, but I will fix those asap
