### ISSUE TITLE
How do I add an Icon to be used by Configurable Build Menus?

### ISSUE THREAD

**Issue by Ratione** [pether-pg/ONI_Mods_byPether#20]
Like, where do I put the file, and what pixel dimensions need to be used?

Additionally, where are the game Icons stored? You use the "icon_errand_art" icon for your default config, but it doesnt seem to be included in the mod files, implying that it was already in the game. Is there a list of those icons somewhere?

**Comment by pether-pg** [comment]
Let me investigate adding new file to have full and correct answer for you. I will answer here once I got something, but I cannot promise any timeline as I'm starting huge house renovation project IRL and modding will be on lower priority.

I found icon_errand_art referenced in game code, similar names include:
icon_errand_dig
icon_errand_farm
icon_errand_ranch
icon_errand_cook
icon_errand_art
icon_errand_research
icon_errand_rocketry
icon_errand_supply
icon_errand_operate
icon_errand_care
icon_errand_tidy

I'm more code guy than artwork guy, but I will talk with friends who are more familiar with game sprites to ask where I can find full list of all available icons

**Comment by pether-pg** [comment]
Using custom icons will be added to the mod in the next update. Please expect steam release later next week.
