### ISSUE TITLE
[Diseases Expanded] Crash while loading a save game 

### ISSUE THREAD

**Issue by tajemniktv** [pether-pg/ONI_Mods_byPether#25]
Whenever I try to load a save, the game crashes. Turning off the mod, fixes it. 

Log: https://paste.ee/p/TtIvi

**Comment by pether-pg** [comment]
Strange, I will investigate that, thanks.
Do you play vanilla or DLC?

**Comment by pether-pg** [comment]
Could not reproduce the issue, but found potential source of it and fixed that. 
Please update your mod to version 2022.3.16.1537
If the issue still appears, please reopen the bug
