### ISSUE TITLE
Private Bedrooms missing default Bedroom Stamina Buffs.

### ISSUE THREAD

**Issue by jwal2tusk** [pether-pg/ONI_Mods_byPether#35]
Both the +2 Morale and +3 Morale Private bedrooms are missing the Stamina recovery buffs that the vanilla Barracks and Bedroom rooms apply. Screenshot of just the difference between +2 Private and Barracks by removing the decor plant. In addition to the buff of the bed type, a Barracks gives +100% stamina recharge and Bedroom +200% stamina recharge. While your private bedrooms offer more morale, you lose these buffs. Could you possibly add +200% to the +2 morale private room and +300% to the +3 morale room as the change is still low percentage but makes the desire to build the rooms more impactful?

Here is also a Francis John Youtube video where he disusses it:
https://youtu.be/Vgglwi7zdHU?t=187

![Stamina_Private](https://user-images.githubusercontent.com/114295927/192100591-ed566654-8029-4a5f-9817-73bbabab03f4.png)
![RoomOverlay_Barracks](https://user-images.githubusercontent.com/114295927/192100592-476a7e9e-fb06-4ff9-9da2-b610b73610d3.png)
![RoomOverlay_Private](https://user-images.githubusercontent.com/114295927/192100595-2915b730-2887-4866-a7a2-b1227d189ace.png)
![Stamina_Barracks](https://user-images.githubusercontent.com/114295927/192100596-e9bba796-86c6-4b65-9887-87a9b153bbfe.png)

**Comment by jwal2tusk** [comment]
Screenshots are in a somewhat confusing order but the hair on the duplicant should help you match the correct one.

**Comment by pether-pg** [comment]
Thanks for the details, the code for that was a little obscured and I missed the details.
I added Private Bedroom stamina effect to my room, it will be included in the next mod update.
