### ISSUE TITLE
Feature Request: Compatibility with Dupes Refrigeration/Advanced Refrigeration Mod

### ISSUE THREAD

**Issue by TroublesomeCorvid** [pether-pg/ONI_Mods_byPether#39]
At this time, your mod doesn't seem to recognize other refrigerators from other mods as being refrigerators, which means refrigerators from other mods are not able to satisfy the requirements for the kitchen room.

Dupes Refrigeration:
https://steamcommunity.com/sharedfiles/filedetails/?id=2021324045

**Comment by pether-pg** [comment]
Hi.
Thanks for the report
After Sweet Dreems update I'm using the same requirement that Klei uses for their Kitchen to make sure both of our rooms align. I intend to keep that approach. 
I will talk to Ronivan to suggest he updated his fridges - I assume they don't work with Klei's Kitchen as well....
