### ISSUE TITLE
Ronivan's mods

### ISSUE THREAD

**Issue by MetaStazz** [pether-pg/ONI_Mods_byPether#40]
I don't use steam....... Would be nice if you can ask Ronivan (As I don't use steam I don't know where to contact him) to put his mods on github or other alternative download place... It's one of the only big Ony modder without alternative download link !
Thanks a lot

**Comment by pether-pg** [comment]
I'm sorry, it was suggested to him a lot, with no effect :( I will try more, it would be really helpful for me as well since I help him sometimes with a code and doing it without github isn't best solution... But I don't expect anything changes soon :(
