### ISSUE TITLE
Rooms Expanded crashes at splash screen

### ISSUE THREAD

**Issue by Laziest-Person** [pether-pg/ONI_Mods_byPether#41]
As the title says, if I enable Rooms Expanded with my other enabled mods, it quickly crashes. I'm trying to single out where there may be a conflict. Any advice, or a fix? Thank you very much for your time, I attached the log below.
[Player-prev.log](https://github.com/pether-pg/ONI_Mods_byPether/files/10279612/Player-prev.log)

**Comment by pether-pg** [comment]
I don't see the crash in this log... 
It is possible that other mod crashed and rooms were blamed for no reason. That may happen after game update, use "Mod Updater" to make sure you have all mods in good version (but it seems your rooms are up to date)

**Comment by Laziest-Person** [comment]
Ah, ok. Sorry for the trouble, I was mostly wondering if I missed something in the log. Thank you for your time, and have a nice day!
