### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by 798924038** [pether-pg/ONI_Mods_byPether#43]
If it can be read in actual time (more frequently than when load game) , like when open the building.
and the resource file can specify a network location, then a more interesting pseudo multiplayer environment can be built.

If you are worried about network problems, you can even use a folder, 
and then create a file with special text as a "request"/"assistance".
To avoid the bugs that may occur when multiple players operate on the same file, the players should wait.
so delete a files when players take a item. one item ,one file is associated with one item.

I hope this issue can inspire you. Many ONI players like this multiplayer environment mod very much

Because of my English level, I use translation tools with some modifications. If there is something you don't understand or make you feel uncomfortable, please forgive me.

    thank you for reading

**Comment by pether-pg** [comment]
Hi
Thanks for suggestions, but I have no plans to expand Multiplayer Storage mod. 
But I currently experiment with other Multiplayer ideas

**Comment by 798924038** [comment]
O(∩_∩)O~
