### ISSUE TITLE
Crash w/ Rooms Expanded

### ISSUE THREAD

**Issue by dezemberr** [pether-pg/ONI_Mods_byPether#46]
Hello! I can load the game and play until I enable Rooms, then the game crashes before reaching the menu.

I'm playing on the base game with several other mods, including Mod Manager, and Rooms is updated.
I've tried moving it toward the top and bottom of the load list and still get the same crash result.

`NullReferenceException: Object reference not set to an instance of an object

UIDupeRandomizer.Apply (KBatchedAnimController dupe, Personality personality) (at <1726ad14e928409087f7fe566b21e0ff>:0)
UIDupeRandomizer.GetNewBody (System.Int32 minion_idx) (at <1726ad14e928409087f7fe566b21e0ff>:0)
UIDupeRandomizer.Start () (at <1726ad14e928409087f7fe566b21e0ff>:0)
FrontEndBackground.Start () (at <1726ad14e928409087f7fe566b21e0ff>:0)

Build: U44-537329-V`

Thanks.

**Comment by andyandybeginner** [comment]
Same here

**Comment by pether-pg** [comment]
Hi, thanks for the report.
I cannot reproduce this issue. Also, I cannot think of any part of my code that could cause this, I don't do anything with UIDupeRandomizer. It is possible that the game blames my mod by mistake.

Could you please:
1. Send me full Player.log file
2. See if the crash continues without Rooms Expanded being enabled

Thanks

**Comment by AlexSteelax** [comment]
[Player.log](https://drive.google.com/file/d/13Zzdx6x2D640IeP_PV8_5pvrwohv5dR9/view?usp=share_link)

OS: Linux

**Comment by dezemberr** [comment]
I finally got around to opening the game. After updating ONI and this mod, it no longer crashes for me. Thanks!
