### ISSUE TITLE
Diseases Expanded Crash on third recipe for mutating virus antivirals

### ISSUE THREAD

**Issue by garrettasplundh** [pether-pg/ONI_Mods_byPether#50]
Crashes on the third mutating virus antivirals recipe. On the one that I guess uses the Swamp Chard Heart. I don't own the DLC. Disabled every mod but Mod updater and Diseases Expanded. Mod updater indicates latest update was applied (April 4th).

Crash text and play log attached.
`NullReferenceException: Object reference not set to an instance of an object

SelectedRecipeQueueScreen.GetIngredientDescriptions (ComplexRecipe recipe) (at <1f4c5a7d658c4522888fade7e74323ad>:0)
SelectedRecipeQueueScreen.RefreshIngredientDescriptors () (at <1f4c5a7d658c4522888fade7e74323ad>:0)
SelectedRecipeQueueScreen.SetRecipe (ComplexFabricatorSideScreen owner, ComplexFabricator target, ComplexRecipe recipe) (at <1f4c5a7d658c4522888fade7e74323ad>:0)
ComplexFabricatorSideScreen.ToggleClicked (KToggle toggle) (at <1f4c5a7d658c4522888fade7e74323ad>:0)
ComplexFabricatorSideScreen+<>c__DisplayClass36_1.<Initialize>b__1 () (at <1f4c5a7d658c4522888fade7e74323ad>:0)
Util.Signal (System.Action action) (at <d35824e72985464e85149179dd14d71e>:0)
KToggle.Click () (at <d35824e72985464e85149179dd14d71e>:0)
KToggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <d35824e72985464e85149179dd14d71e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U46-552078-VD`

[Player.log](https://github.com/pether-pg/ONI_Mods_byPether/files/11302674/Player.log)

Thanks and good luck!

**Comment by pether-pg** [comment]
Thanks for the report, I can see the issue in my code, I should release fix soon
