### ISSUE TITLE
Configurable Build Menus with modded content

### ISSUE THREAD

**Issue by llunak** [pether-pg/ONI_Mods_byPether#53]
It seems that Configurable Build Menus does not handle properly buildings from mods and they are always placed first in the menu. I've tried with "Starmap POI Capacity Sensor" from Rocketry Expanded or buildings from the Fluid Shipping mod.

My config file [ConfigurableBuildMenus.Config.json.txt](https://github.com/pether-pg/ONI_Mods_byPether/files/11902275/ConfigurableBuildMenus.Config.json.txt) and log file [Player.log.txt](https://github.com/pether-pg/ONI_Mods_byPether/files/11902285/Player.log.txt). The only new content is at the end, and I'm certain the file is loaded.

I also suggest changing the patch for GeneratedBuildings.LoadGeneratedBuildings() from a postfix to a finalizer, to ensure it's run last. Some mods patch the function to add their building and whether this mod sees changes by such mod depends on the mod load order.

**Comment by llunak** [comment]
Upon further inspection this seems to be caused by building subcategories. Those modded buildings do not set it and so end up as "uncategorized", which apparently go first. Setting them to a proper category makes them placed properly. So strictly speaking not a bug of this mod.

On the other hand, if sorting depends on subcategory, then "JustAfter" key doesn't really work. Presumably a proper fix would be for this mod to implement also optional "Category" key that'd allow overriding it.

**Comment by llunak** [comment]
> Upon further inspection this seems to be caused by building subcategories. Those modded buildings do not set it and so end up as "uncategorized", which apparently go first. Setting them to a proper category makes them placed properly. So strictly speaking not a bug of this mod.

Actually the mod is buggy there, it discards a subcategory even when the mods are fixed to provide the proper subcategory. => #54 

> On the other hand, if sorting depends on subcategory, then "JustAfter" key doesn't really work. Presumably a proper fix would be for this mod to implement also optional "Category" key that'd allow overriding it.

This is unchanged by this, so I'll leave this issue open.

**Comment by pether-pg** [comment]
Hi, thanks for the report and suggestions, I will look into it once I had some time for modding

**Comment by llunak** [comment]
Actually the category support was pretty simple to add, so => #56. It also handles the category-discarding bug, and being able to specify a category also helps with mods that do not specify it.

The mod should still work out-of-the box for vanilla buildings. For the mod description on Steam, you can edit "If you don't know exact values for menu/building Ids, you can check them in ConfigurableBuildMenus.ExistingBuildingIDs.json file" to say that it applies to categories as well ("Value"). Cross-mod compatibility section can now probably also say that it should work in general, possibly needing explicit category. For me personally it now works fine with 3 mods (Rocketry Expanded, Fluid Shipping, Insulated Doors).

**Comment by pether-pg** [comment]
Thanks for PRs, I was able to merge them with my project. I aslo added even more control over custom categories, with possibility to define new ones. It seems to be working just fine. Could you give one final look to confirm that current mod version solves all your issues and wishes before I release it? thanks!

The config generated by default is also changed a little, to see it make sure you removed your previous config.

[ConfigurableBuildMenus_beta_2023.07.05.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/11957965/ConfigurableBuildMenus_beta_2023.07.05.zip)

**Comment by llunak** [comment]
My PRs solve all my problems here, so with them merged it should all fine for me :). I've skimmed over the recent changes and it looks ok to me.

**Comment by pether-pg** [comment]
Issue should be fixed with recent update
