### ISSUE TITLE
Mission Control Station not recognizing transparent ceiling

### ISSUE THREAD

**Issue by ShadowKitty42** [pether-pg/ONI_Mods_byPether#57]
As the title says, I have it in a room with clear visibility to space and it's giving me this error
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/3394296/7d8f1031-b47f-4005-9cda-8570da4b19b6)

**Comment by pether-pg** [comment]
Your room has abyssalite ceiling. You must make all ceiling tiles transparent (even if the tile above is not transparent):
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/77891249/e1821d98-4d65-4af4-bb50-273763e412cf)
