### ISSUE TITLE
Museum and Space Museum bonus doesn't work

### ISSUE THREAD

**Issue by rick50611** [pether-pg/ONI_Mods_byPether#61]
I try only use "Mod Updater" and "[Vanilla + DLC] Rooms Expanded" and updat this.
Can get room but doesn't give any moral bonus in "Morale"

https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/3e9b9cfd-81bf-4d35-9386-67c588c40465
![20230906234810_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/dffab3f4-b44a-4218-a11f-34b52515d0ab)
![20230906234811_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/a372b438-c605-4518-830b-b49dd61b64c3)
![20230906234548_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/9af9418f-9266-4301-92d3-ac47e3bf5f66)
![20230906231729_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/1bc0435a-4fc3-4859-8c4a-a251d78ba6d9)

**Comment by pether-pg** [comment]
Thanks for the screens. That super strange, it works for me, I will investigate.
Did you modify settings somehow? I can see your room screen showing +100% bonus, when your settings are at +30%
Stupid question - what will happen if a duplicant exits and reenters the room?

**Comment by rick50611** [comment]
this is different time , first time is+30%bonus but  doesn't work, after this I try to use +100%
I try exits and reenters the room after this is nothing

And after that I saw 1 interesting question, 
I usually us Chinese language, when I try to cheng language to English and resistan all game aften this I saw this bouns.
Then I try to cheng language to Chinese again then bouns is missing

**Comment by pether-pg** [comment]
hm, that's good to know, thanks!

**Comment by pether-pg** [comment]
Could you please Player.log from the game when you didn't get Museum bonus? Thanks

**Comment by rick50611** [comment]
[Player.log](https://github.com/pether-pg/ONI_Mods_byPether/files/12550170/Player.log)

**Comment by pether-pg** [comment]
[RoomsExpanded_2023_09_07.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/12552221/RoomsExpanded_2023_09_07.zip)
Could you please give this beta a try? I believe it should fix your issue

**Comment by rick50611** [comment]
Bouns Can work Thank!
![20230908204911_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/c48d1464-2010-419d-a952-00923e9c819a)
![20230908205019_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/6a24b46c-aa4e-4afd-b186-f5eea41814e6)
![20230908205021_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/144262500/293c6d35-5be0-4777-ae9f-4ad17b6bddbd)

**Comment by pether-pg** [comment]
Fix released with 2023.9.12.2053 mod version
