### ISSUE TITLE
Please make it possible to add a translation.

### ISSUE THREAD

**Issue by LeonusDH** [pether-pg/ONI_Mods_byPether#63]
Please make it possible to add other languages.

**Comment by pether-pg** [comment]
Most mods already have this feature. Could you provide more information?

**Comment by LeonusDH** [comment]
I would like to add translation to some of your mods. But I don't see a folder with localization files in them.
I'm not quite sure how much more information can still be provided.

**Comment by pether-pg** [comment]
Please give me the names of the mods that lack translation support, I will add it

**Comment by LeonusDH** [comment]
Configurable Build Menus

**Comment by pether-pg** [comment]
There isn't much to translate there ;)

**Comment by LeonusDH** [comment]
The little things are worth translating too)

**Comment by pether-pg** [comment]
[ConfigurableBuildMenus_beta_2023.11.8.2029.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/13301200/ConfigurableBuildMenus_beta_2023.11.8.2029.zip)

Please check if this solution satisfies you. If I missed anything that you would like translated, please let me know

**Comment by LeonusDH** [comment]
> [ConfigurableBuildMenus_beta_2023.11.8.2029.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/13301200/ConfigurableBuildMenus_beta_2023.11.8.2029.zip)
> 
> Please check if this solution satisfies you. If I missed anything that you would like translated, please let me know

It looks like everything's fine.

**Comment by pether-pg** [comment]
Great, thanks for confirmation. I will release translations alongside next mod update, I prefer to keep number of updates low as they tend to mess with people's config files
