### ISSUE TITLE
Disease Expanded crashes the game

### ISSUE THREAD

**Issue by aantono** [pether-pg/ONI_Mods_byPether#64]
Getting the crash with the following log error:

[Player.log](https://github.com/pether-pg/ONI_Mods_byPether/files/13261017/Player.log)

**Comment by aantono** [comment]
Looks like Rooms Expanded also crashes after the October 2023 update.
[Uploading Player-prev.log…]()

**Comment by pether-pg** [comment]
Are you sure you have the most recent mod version? Please use "Mod Updater" mod to enforce mod update.

**Comment by pether-pg** [comment]
Rooms log seems not attached correctly. Please open new issue for it and attach it correctly, but things may be unstable on beta branches and they are not supported by my mods

**Comment by pether-pg** [comment]
New version of the mod just got released
