### ISSUE TITLE
Biobot Contracts Sleeping Curse and Crashes the Game

### ISSUE THREAD

**Issue by TroublesomeCorvid** [pether-pg/ONI_Mods_byPether#69]
Yyyyyyyyyep.  There it is.

![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/54051273/d8b7c896-3194-4d8d-bad5-30192aee646c)

When nappy-times comes, it crashes the game.

![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/54051273/9790d0aa-3064-4b8c-981b-1c2153e75945)

Player.log file attached.  Thanks in advance!
[Player.log](https://github.com/pether-pg/ONI_Mods_byPether/files/13763248/Player.log)

**Comment by pether-pg** [comment]
The fix just got released, please update your mod to 2024.1.5.1035 version.
Previously infected biobots will not be magicly cured. You must disable Sleeping Curse in mod options, save the game without it and re-enable after that. That should cure the bots
