### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by icuurd12b42** [pether-pg/ONI_Mods_byPether#7]
https://youtu.be/0_eXpxwfV84

MissingMethodException: UnityEngine.GameObject SeedProducer.ProduceSeed(string,int)

(wrapper dynamic-method) SeedProducer.CropPicked_Patch1(object,object)
SeedProducer+<>c.<.cctor>b__15_1 (SeedProducer component, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Creatures/common/SeedProducer.cs:44)
EventSystem+IntraObjectHandler`1[ComponentType].Trigger (UnityEngine.GameObject gameObject, System.Object eventData) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:109)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:146)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:411)
Crop.SpawnConfiguredFruit (System.Object callbackParam) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Creatures/common/Crop.cs:81)
Scheduler.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/ai/scheduler/Scheduler.cs:113)
GameScheduler.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/ai/scheduler/GameScheduler.cs:38)

**Comment by icuurd12b42** [comment]
It worked for a while... Then it started to crash, the first time was while doing vent or pipe research. but it looks like any research will make it crash. Possible started to crash when I added the second lab. will investigate further.

**Comment by icuurd12b42** [comment]
I removed the Supercomputer and it also crashes about the same time after I start the research

MissingMethodException: UnityEngine.GameObject SeedProducer.ProduceSeed(string,int)

(wrapper dynamic-method) SeedProducer.CropPicked_Patch1(object,object)
SeedProducer+<>c.<.cctor>b__15_1 (SeedProducer component, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Creatures/common/SeedProducer.cs:44)
EventSystem+IntraObjectHandler`1[ComponentType].Trigger (UnityEngine.GameObject gameObject, System.Object eventData) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:109)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:146)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:411)
Crop.SpawnConfiguredFruit (System.Object callbackParam) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Creatures/common/Crop.cs:81)
Scheduler.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/ai/scheduler/Scheduler.cs:113)
GameScheduler.Update () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/ai/scheduler/GameScheduler.cs:38)

**Comment by icuurd12b42** [comment]
Sorry, I have the wrong version. My dyslexia was reading the version reference from the other guy's post in the discussion...

![image](https://user-images.githubusercontent.com/6321426/118860786-c9d38b00-b8a9-11eb-9a59-a4f5f386ab5c.png)

Do you have the binary available somewhere for manual install?

**Comment by pether-pg** [comment]
1. It seems that all my versions of the mod have Product version 2020.1.25.0, I must fix that, thanks. Anyway, this says nothing
2. On the yt movie I see you are using RoomsExpanded.dll, but after recent update it will be named RoomsExpandedMerged.dll as I merge it with PLib for option generation. So this is confirmation that you are using old mod, and it should be updated.
3. If you want to make local install of the mod, use files from https://github.com/pether-pg/ONI_Mods_byPether/tree/master/UploadFiles_Steam/RoomsExpanded - those are the same I update on steam
4. However, I'd suggest to use "Mod Updater" mod https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283 as it can force other mods to update. This will save you from messing with local install and will be usefull in the future as well. 10/10, I cannot say how good mod that is.
5. On the yt I can see that nobody tried to harvest anything, and this was the reason for crash before the update, so there is a risk there could be another issue on the table. Could you please provide full Player.log? Thanks!

**Comment by icuurd12b42** [comment]
I installed Mod Updater. It listed 8 "out of date" mods... Forcing Update and restarted the game 8 times to match, each time the count went down by one. When there was 3 left, your mod was listed as needing update... When there was 2 left, your mod was listed as needing update again, and again for the last one. it looks like your mod took 3 spots. Anyway I have the right dll now.

I have to assume the game crashed storing an arbor tree seed in the storage. it's the only plant related action that happened. Pretty much redid the exact same set of actions testing this, the resulting ne storage had a arbor tree seed in it. so problem solved it works.

In the video you see I setup a room for the Crafting Station. I suggest a "Workshop" room would be something to add

Also I setup a room for the crusher. would be nice to have a "Machine" room

Anyways. thanks for the fix. these mods must be a nightmare to maintain.

**Comment by pether-pg** [comment]
So if I understand correctly, updating the mod fixed the issue? Great :)

Workshop room is somthing to be considered, nice idea :) For rock crusher I got Industrial Room, grants no effect, but you may enable it to make room overlay more vivid :)

Thanks

**Comment by icuurd12b42** [comment]
Yes, take care
