### ISSUE TITLE
Germ Catcher does not draw any power (Diseases Expanded)

### ISSUE THREAD

**Issue by UnderwearApp** [pether-pg/ONI_Mods_byPether#70]
Although the germ catchers should draw 120W, it seems they are not drawing any power at all. Have rebuilt, reloaded, etc. Not sure if a log would be helpful in this case but can provide one or screenshot if that might help.

They otherwise function as expected, drawing in germs and dropping flasks when full.

**Comment by pether-pg** [comment]
Thanks, I confirm I can reproduce the issue. Nice catch! I will investigate why is it happening.
No logs are required

**Comment by pether-pg** [comment]
The fix just got released, please update your mod to 2024.1.5.1035 version
