### ISSUE TITLE
RoomsExpanded broken order of rooms

### ISSUE THREAD

**Issue by realwiseserpent** [pether-pg/ONI_Mods_byPether#93]
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/74019811/59de9f73-a825-40bc-b248-2a0119476791)
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/74019811/67eaa452-cf64-488e-bf33-2d7d8f7cb241)
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/74019811/bf12f3c5-be85-4f2f-802b-ff80e99a64b9)

**Comment by pether-pg** [comment]
Thanks for the report, index issue got fixed and will be released in next mod update:
![image](https://github.com/pether-pg/ONI_Mods_byPether/assets/77891249/4954aa1c-8894-47ee-8adf-ee91e33096fc)
